repos:
  - repo: https://github.com/domodwyer/pre-commit
    rev: v3.5.0
    hooks:
      - id: r-stylr
        stages: [commit, push]
      
      - id: r-lintr
        stages: [commit, push]
      
      - id: r-readme
        stages: [commit, push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit, manual]
      - id: check-json
        stages: [commit, manual]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        stages: [commit, manual]
      - id: check-merge-conflict
        stages: [commit, manual]
      - id: mixed-line-ending
        args: ["--fix=no"]
        stages: [commit, manual]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]